export const ADD_INGREDIENT = 'ADD-INGREDIENT';
export const REMOVE_INGREDIENT  = 'REMOVE-INGREDIENT';
export const SET_INGREDIENTS = 'SET-INGREDIENTS';


export const PURCHASE_BURGER_SUCCESS='PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAILURE='PURCHASE_BURGER_FAILURE';
export const START_PURCHASE_BURGER='START_PURCHASE_BURGER';
export const PURCHASE_INIT='PURCHASE_INIT';


export const FETCH_ORDER_START='FETCH_ORDER_START';
export const FETCH_ORDER_SUCCESS='FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAIL='FETCH_ORDER_FAIL';


export const AUTH_START='AUTH_START';
export const AUTH_SUCCESS='AUTH_SUCCESS';
export const AUTH_FAIL='AUTH_FAIL';
export const LOGOUT='LOGOUT';

export const AUTH_REDIRECT_PATH='AUTH_REDIRECT_PATH';
